### PR TITLE
Login Theme updated

### PR DESCRIPTION
**Pull request by Dharmik98**
No issue.

Changes: Login UI updated

Screenshots/GIF for the change: 
screenshot_2018-05-30-13-31-32-981

### CODE REVIEW

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale What are your views?

**Comment by harshvardhan-takawale** [comment]
Can we have something in the background, some design or some color gradient? This looks a bit empty. Something like this 
screenshot_20180604-135931

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale I think you should now be able to push to this PR. Please make changes as you suggested for the background and attach a screenshot so that we can finalize.

**Comment by brijeshshah13** [comment]
@Dharmik98 Follow [commit style](https://github.com/brijeshshah13/OpenCI/blob/development/assets/commitStyle.md) from next time.

**Review by brijeshshah13 — APPROVED** [review]
Nice work!

**Pull request merged**
