### PR TITLE
feat: Travis CI script

### LINKED ISSUE #10: Integrate Travis CI script for builds
**Is it a ?**

- [ ] Bug Report

- [x] Feature Request
    
- [ ] Chore
    
### Feature Request

**Feature Description**

Integrate Travis CI script for testing the app builds.
   
**Would you like to work on the issue?**

Up for grabs.

### PR DESCRIPTION
**Pull request by harshvardhan-takawale**
Changes: 
I have created the script. Please let me know if there are some errors, and I was not very sure what to add in the `script` section, please tell me if something needs to be added.

Fixes #10

### CODE REVIEW

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale You need to add the remaining licenses and change the `script` section according to this [file](https://gist.github.com/harmittaa/7d3c51041ffd0e54cda9807e95593309#file-travis-yml), specify system images as shown in the last part of the [overview](https://docs.travis-ci.com/user/languages/android/#Overview) section for API levels 16 and 26 and use `env` section to declare global variables ANDROID_BUILD_TOOLS_VERSION=26.0.2 ANDROID_API_LEVEL=26 and use them in `components` as [this](https://github.com/fossasia/open-event-android/blob/development/.travis.yml) script. And please follow the [commit style](https://github.com/brijeshshah13/OpenCI/blob/development/assets/commitStyle.md).

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale As you can notice, the Travis CI build is failing because it doesn't have the permission to run the `./gradlew` command. Hence you need to add the following lines to give the necessary access:
```
before_install:
 - chmod +x gradlew
```

**Comment by brijeshshah13** [comment]
@harshvardhan-takawale Please check the build log and try to fix the following warning:

`Warning: retrofit2.Platform$Java8: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement`

I tried to fix it by adding a `-dontwarn` and `-keep` flags for that class but it isn't working out. See if you can find a solution to suppress that warning.

**Comment by harshvardhan-takawale** [comment]
@brijeshshah13 I am not able to get it done.

**Pull request closed without merging**
